"""Add age, weight, breed, parents

Revision ID: 8fbc8e6f111e
Revises: 59c14d866340
Create Date: 2025-06-05 10:38:22.315491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbc8e6f111e'
down_revision = '59c14d866340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheep', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('breed', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mother_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('father_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sheep_mother_id', 'sheep', ['mother_id'], ['id'])
        batch_op.create_foreign_key('fk_sheep_father_id', 'sheep', ['father_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sheep', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('father_id')
        batch_op.drop_column('mother_id')
        batch_op.drop_column('breed')
        batch_op.drop_column('weight')
        batch_op.drop_column('age')

    # ### end Alembic commands ###
